### ISSUE TITLE
Support ARM64 (Multi arch)

### ISSUE THREAD

**Issue by jakobhviid** [jakobhviid/Kafka-Docker#6]
The image should support ARM64 and have a multi-architecture image.
https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by olnor18** [comment]
The images should be build for different architectures, so they can be used on devices such as Raspberry pies which can both be arm32 and arm64. They should therefore be build using buildx for multi-architecture support and pushed to docker hub so the docker-compose can be used without modifications on different architectures.

**Comment by jakobhviid** [comment]
the secrets have been added.

**Comment by dstoft** [comment]
@olnor18 I have pushed the multiarch version, which supports amd64, arm/v7 and arm64. The dockerhub tag for this multiarch build is "cfei/kafka:latest-multiarch". Would you mind testing it for me on a Raspberry Pie?

**Comment by olnor18** [comment]
@dstoft Jeg kan køre imaget på en arm32/v7 men da zookeeper også mangler en multiarch, kan jeg ikke teste om det egentlig virker. Kan dog konstatere at Kafka:2.0.0-beta fejler med exec format error før den overhovedet når til zookeeper connection check, som er der hvor Kafka multiarch dør

**Comment by jakobhviid** [comment]
det er en god pointe - zookeeper skal der ske det samme for.

**Comment by dstoft** [comment]
@olnor18 I think "arm/v7" means v7 of arm32. I have build and pushed the multiarch version of Zookeeper as well with "cfei/zookeeper:latest-multiarch".

**Comment by olnor18** [comment]
Arm v7 and below only support 32 bit instructionsets so i just refer to arm/v7 as arm32v7 for clarifying that it is for 32 bit devices. I will check the full stack of zookeeper and kafka later on a armv7 pi as well as an amd64 machine

**Comment by dstoft** [comment]
Arh, that makes sense, thank you for clarifying my confusion. And great, let me know how it goes!

**Comment by olnor18** [comment]
The images seem to work, although i have some issues, due to the lower limit of 3GB of ram for kafka, which the Raspberry Pi 4, with 4GiB of ram, can't handle. This issue can now be closed, as far as I can see

**Comment by dstoft** [comment]
Yea, I saw that issue mentioned other places as well when implementing this. I'm closing this issue now :)
